spring.application.name=resumebuilder
spring.main.allow-circular-references=true

# ?? Server ??????????????????????????????????????????????
server.port=8080

# ?? H2 In-Memory Database ????????????????????????????????
spring.datasource.url=jdbc:h2:file:./data/resumedb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
# And change create-drop to update so tables persist:
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ?? JWT ??????????????????????????????????????????????????
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# ?? OpenAI ???????????????????????????????????????????????
openai.api-key=openai.api-key=${OPENAI_API_KEY}
openai.url=https://api.openai.com/v1/chat/completions
openai.model=gpt-4o-mini

# ?? Gmail SMTP ???????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=avifullstackdev@gmail.com
spring.mail.password=Avin@0501
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? App URLs ?????????????????????????????????????????????
app.base-url=http://localhost:3000
app.backend-url=http://localhost:8080