spring.application.name=resumebuilder
spring.main.allow-circular-references=true
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

openai.api-key=${OPENAI_API_KEY}
openai.url=https://api.openai.com/v1/chat/completions
openai.model=gpt-4o-mini

app.base-url=${APP_BASE_URL}
app.backend-url=${APP_BACKEND_URL}

sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_FROM_EMAIL}